const epipelagic_general = "The depth ranging from the surface of the ocean to about 200 meters below said waters is known as the Epipelagic Zone, or the Sunlight Zone. The average temperatures seen in this region are about 36 degrees Celsius near the Persian Gulf and -2 degrees Celsius near the North Pole (NWS, n.d.). This area has high levels of sunlight that penetrate these surface waters allowing for productivity through the process known as photosynthesis. However, the boundary between this zone and the next, the Mesopelagic, is subjected to decreasing amounts of dissolved oxygen on account of the lack of photosynthetic algae as levels of sunlight decrease (Thurman, Harold, Trujillo, Alan; 2011). While productivity decreases the deeper you get, the Epipelagic Zone is home to a wide array of animals that many of us are familiar with due to popular media."
const epipelagic_marine = "Many of the organisms that live and migrate in this zone rely on both sunlight and closeness to the surface. When one thinks of ocean creatures we think big: whales, sharks, dolphins, or even tuna. Yet, this is also home to corals, seaweed, and phytoplankton. With corals we get beautiful coral reefs, such as the Great Barrier Reef in Australia, which are home to various marine animals and make for ample areas for spawning and hunting for many of these species. Phytoplankton are a food source for many animals of this area and actually produce much of the oxygen that goes into the atmosphere, so they’re a vital part of the ocean and the Earth itself (Fothergill, Alastair; 2001)";
const epipelagic_media = "Now going back to how popular media has familiarized us to many of the ocean’s marine animals we can look at some portrayals of such animals previously mentioned in the epipelagic zone. A good example of this is in Finding Nemo which does a great job of introducing kids to marine life including: coral reefs, whales, sharks, jellyfish, sea turtles, etc while following a clownfish’s quest across the ocean in order to find his son. If we go the horror route many of us are familiar with the Jaws movies which focuses on a bloodthirsty shark that attacks beachgoers (which is not very accurate scientifically, but it terrified many children and adults for a while). The DC Film Aquaman also presents some animals as well throughout the movie even though they are not the main focus. In the background of Aquaman, one is consistently introduced to dolphins, sea horses, sea turtles, stingrays, small fish, and whales. While any of these movies at least give people some idea of the different forms of life there are in our oceans one should remember that these are still movies and 1) marine animals do not talk and joke around (unless it is through echolocation) 2) sharks do not actively attack boats and people for malicious reasons and 3) sea animals are not steads for battle.";
const mesopelagic_general = "Now in the depth ranging from 200-1,000 meters lies the Mesopelagic Zone, otherwise known as the “Twilight Zone.” Temperatures in this zone are rather variant as this is where the Thermocline, which is a layer that marks rapidly changing temperatures with depth as a way to isolate warmer surface waters from the colder waters of the deep (Thurman, Harold, Trujillo, Alan; 2011). The lack of sunlight also means that many of the animals that depend on phytoplankton migrate up to the surface waters to feed under the cover of nightfall (Oceana; 2012). The darkness that begins to take hold in this zone also means that organisms that call this area home have acquired some interesting adaptations to compensate for the lack of light.";
const mesopelagic_marine = "Animals that inhabit the Twilight Zone have a rather simple goal: be able to see while not being seen yourself. In order to accomplish this many organisms have actually become transparent, developed sensitive large eyes, and have bioluminescence. Hatchetfish have sensitive eyes and their own way of blending into their surroundings called countershading, in which its body matches the light coming from the surface waters to protect its underbelly (Fothergill, Alastair; 2001). Squids in this area have also become transparent and notably “softer” than their relatives in the upper regions to compensate for the increasing pressure that is found the deeper one gets (Fothergill, Alastair; 2001). You still find jellies, such as the Comb Jellyfish, that lay out sticky “nets” to secure the prey that blend into the surrounding waters along with some ability to use bioluminescence to help them navigate this area. ";
const mesopelagic_media = " The fact that many of these animals have adapted to these dark waters by becoming transparent and/or developing large encompassing eyes would draw the attention of any writer or director. The spine-chilling franchise Alien is thought to have drawn inspiration from a parasite called the Phronima. In particular, many feel that in Alien, 1986, the Queen Xenomorph was what came into fruition based on the Phronima due to the design of the creature. Taking a closer look at the the animals itself one can’t help but draw similar traits presented when compared to the xenomorphs: it hollows out its prey, lays its eggs, and when the young hatch inside the body is food for these amphipods (Scripps Institution; n.d.).";
const bathypelagic_general = " The depths of 1,000-4,000 meters are referred to as the Bathypelagic Zone, or the “Midnight Zone.” Temperatures here are always hovering around 4 degrees Celsius and the pressure is immense, 5850 lbs per square inch (NWS; n.d.). Organisms at these depths deal with the complete lack of light as well as even sparser resources so they must utilize every adaptation that they have in their arsenal to survive in these harsh depths.";
const bathypelagic_marine = " Within these depths of the ocean many of this zone’s inhabitants have a number of traits that help them survive: dark red bodies, rod-like bodies, organs sensitive to tiny movements, and bioluminescence. The dark red bodies are an excellent form of camouflage for both predators and prey as sunlight has a distinct red hue, and as no sunlight can penetrate these depths the red color makes these animals virtually invisible to others (Fothergill, Alastair; 2001). Predators benefit from having rod-like bodies, that help them move around quickly, sensitive organs, which aid in finding prey (Fothergill, Alastair; 2001). Yet, bioluminescence can be beneficial to both predator and prey if one considers it. Prey animals use bioluminescence to communicate with others of its kind and confuse the predators that harness it to lure in their prey. Hairy Angler Fish use their  glowing “lure” to attract its prey closer to itself wherein its “hairs” detect when it is close enough to grab as it waits in the darkness. Another unique animal called the Gulper Eel has a gigantic mouth that remains open to catch prey that can sometimes be as big as itself. These depths contain numerous other bizarre creatures which we hope you try to discover as well.";
const bathypelagic_media = "Once again turning to the movie Finding Nemo there is a certain scene that everyone remembers from this masterpiece as it scarred many of us as children. That’s right, it's the scene with the angler fish! The way it was set is rather perfect as both Marlin and Dory seem to be rather mystified by the “light” they encounter, just like prey in real life, and try to touch it due to such, but are horrified to find a terrifying angler attached. Another good source that shows aspects of the Midnight zone and its inhabitants is Aquaman. In a scene in which both Aquaman, or Arthur, and his companion Mera are setting off to “The Trench,” when they encounter numerous creatures that attack them. Looking at the creatures you can see that parts of them are red, which is how many animals in the Bathypelagic zone camouflage themselves, and seem to have an aversion to bright light, possibly due to them being from an area that lacks such.";
const abyssopelagic_general = "The final zone that will be covered is the Abyssopelagic Zone, or affectionately called “The Abyss.” Its depths range from all parts of the ocean below 4000 meters to the seafloor, and is always at near freezing temperatures (NWS; n.d.). This zone is also categorized as the Abyss, because of the lack of life found here due to the combination of lack of sunlight, freezing temperatures, and immense pressure. However, due to extensive research there have been some species that are able to survive under these harsh conditions.";
const abyssopelagic_marine = "It has been discovered that due to the deep sea vents that occupy these deep waters organisms such as: White Crabs, Tube Worms, and even Mussels have been able to find a relatively sufficient source of food. These vents excrete bacteria which derive energy from the sulfides that are found within them, and as this bacteria multiplies they form “mats” which some of these animals graze upon and give predators opportunities to eat other organisms that eat the bacteria (Fothergill, Alastair; 2001).";
const abyssopelagic_media = "Not many movies or similar media focus too much on the bottoms of the sea and if they do so it is rather difficult to discover if they are actually set here. So if we look back on that earlier deep sea scene in Aquaman once again they are trying to get to the Trench meaning it is very deep down. Due to the complete lack of sunlight and the formation of said trench when they reach it we can speculate that they may be at the bottom of the ocean. Now, also with some speculation, another film that makes one wonder how deep they really are is The Abyss. First, we would like to point out that the title is very promising already as it implies that they are in fact in the abyss, or very very deep down. There is also a scene in which a member of the crew in the movie is taken from an area wherein there is no light, save from inside his suit and from the “alien” that takes him which looks much like a Comb Jellyfish but with its own unique qualities. Even if they are not in the abyss as he is able to use a suit in this area, but even specialized submarines have trouble with the sheer pressure of these depths we should remember it is a fictional movie that was made in 1989.";

export{
    epipelagic_general,
    epipelagic_marine,
    epipelagic_media,
    mesopelagic_general,
    mesopelagic_media, 
    mesopelagic_marine,
    bathypelagic_general,
    bathypelagic_marine, 
    bathypelagic_media,
    abyssopelagic_general,
    abyssopelagic_marine,
    abyssopelagic_media
};